### PR TITLE
add CI

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit d722ea5 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit d722ea5 with merge d722ea5...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/cuda/builds/237242397?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d722ea5aad6b93fa8a41a243ad31c5000cf5f822 to master...

**Pull request merged**
